tier4/AutowareSignage

src/signage/src/signage/view_controller.py

change default name for route

---

src/signage/package.xml
src/signage/src/signage/announce_controller.py
src/signage/src/signage/autoware_state_interface.py

Change message type to universe message type

change to universe message type

---

src/signage/src/signage/signage_utils.py

fix getting station format

---

src/signage/package.xml
src/signage/src/signage/announce_controller.py
src/signage/src/signage/autoware_state_interface.py
src/signage/src/signage/route_handler.py

need this PR
https://github.com/tier4/tier4_ad_api_adaptor/pull/16

add back door announce

---

.github/PULL_REQUEST_TEMPLATE.md

add template

---

src/signage/src/signage/route_handler.py

fix: fix minor bug from the test

---

README.md

Add FMS_URL description to change other FMS Domain.

Add FMS_URL description

---

src/signage/src/signage/route_handler.py

fix remain_arrive_time_text do not reset

---

signage.repos

* update repos
* sync msgs with the main

stage release for test

---

.beta.repos
.github/scripts/update_beta_branches.sh
.github/workflows/update-beta-branch.yaml
README.md

- ci sync for the signage.repos, to define the hash code for each repos
- update README

chore: add auto sync

---

.github/workflows/update-beta-branch.yaml

chore: add back workflow dispatch in order to trigger in github

---

.beta.repos
signage.repos
src/signage/launch/signage.launch.xml
src/signage/package.xml

- merge after the boot shutdown 

feat [signage]: add launch from boot_shutdown_tools

---

src/signage/resource/page/AutoDriving.qml
src/signage/resource/page/BusMoveView/BusRouteName.qml
src/signage/resource/page/BusMoveView/BusStopList.qml
src/signage/resource/page/BusStopView/BusRouteName.qml
src/signage/resource/page/BusStopView/BusStopName.qml
src/signage/resource/page/ManualDriving.qml
src/signage/resource/page/OutOfService.qml

fix signage display ratio

---

src/signage/package.xml
src/signage/src/signage/autoware_state_interface.py

- fix the emergency not able to get correctly

fix emergency stop

---

.github/scripts/update_beta_branches.sh
src/signage/package.xml
src/signage/resource/page/AutoDriving.qml
src/signage/resource/page/BusMoveView/BusRouteName.qml
src/signage/resource/page/BusMoveView/BusStopList.qml
src/signage/resource/page/BusStopView/BusRouteName.qml
src/signage/resource/page/BusStopView/BusStopName.qml
src/signage/resource/page/BusStopView/TimeRemaining.qml
src/signage/resource/page/ManualDriving.qml
src/signage/resource/page/OutOfService.qml
src/signage/src/signage/autoware_state_interface.py
src/signage/src/signage/route_handler.py

Sync beta/v2.0.0

---

.github/scripts/update_beta_branches.sh
src/signage/package.xml
src/signage/resource/page/BusStopView/TimeRemaining.qml
src/signage/src/signage/autoware_state_interface.py
src/signage/src/signage/route_handler.py

Sync develop stage

---

src/signage/config/signage_param.yaml

- [INTERNAL_LINK](https://tier4.atlassian.net/browse/T4PB-26256)
- change the screen resolution to 1920x540 

chore: change screen default ratio

---

src/signage/config/signage_param.yaml
src/signage/resource/page/BusMoveView/BusRouteName.qml
src/signage/resource/page/BusStopView/TimeRemaining.qml
src/signage/src/signage/announce_controller.py
src/signage/src/signage/autoware_interface.py
src/signage/src/signage/autoware_state_interface.py
src/signage/src/signage/parameter_interface.py
src/signage/src/signage/ros_service_interface.py
src/signage/src/signage/route_handler.py
src/signage/src/signage/signage.py
src/signage/src/signage/signage_utils.py
src/signage/src/signage/view_controller.py

- refactoring and add new api 

feat: refactoring and new api

---

src/signage/src/signage/route_handler.py
src/signage/src/signage/signage_utils.py

- fix previous station not removed when schedule is changed

fix: test bug

---

src/signage/src/signage/ros_service_interface.py
src/signage/src/signage/route_handler.py
src/signage/src/signage/signage.py
src/signage/src/signage/signage_utils.py

sync: develop from stage

---

src/signage/src/signage/autoware_interface.py

- make the autoware connection checking time longer, as it does not need to be real time

make the autoware connection checking longer

---

src/signage/src/signage/route_handler.py

- add announce early for the first engage

add announce early for the engage

---

src/signage/src/signage/signage_utils.py

fix: 発車予告のテキストを修正

---

src/signage/config/signage_param.yaml
src/signage/src/signage/announce_controller.py
src/signage/src/signage/route_handler.py

次の車両は防音性が高いため外の音が聞こえない
発進発話などが車内で聞こえるようにサイネージの発話設定を変更する
また、到着時の発話の条件と発話内容の変更を行った

feat: 新車両向けにstand aloneの設定と音声発話を修正

---

src/signage/src/signage/route_handler.py

- do not announce when the operation mode is stop

do not announce emergency when stop mode!
